// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jrascraping.Models;

namespace jrascraping.Migrations
{
    [DbContext(typeof(JraDbContext))]
    partial class JraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("jrascraping.Models.CnameTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Racename")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CnameTable");
                });

            modelBuilder.Entity("jrascraping.Models.RaceResults", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Racename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.Property<int>("Waku")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("Corner")
                        .HasColumnType("TEXT");

                    b.Property<string>("F_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("H_weight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jockey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Margin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Num")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trainer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Racename", "Place", "Waku");

                    b.ToTable("RaceResults");
                });
#pragma warning restore 612, 618
        }
    }
}
