@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/api/groups HTTP/1.1

###
POST http://{{host}}/api/groups HTTP/1.1
content-type: {{contentType}}

{
    "id": 4,
    "name": "group3"
}