@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
POST http://{{host}}/api/token HTTP/1.1
content-type: {{contentType}}

{
    "empId": "1234",
    "empPassword": "1234"
}